Page format button
sitn/geoshop2 pull request #131
Opened 2020-11-24 11:15 UTC by kalbermattenm

This implements #122

Currently we are still missing the interaction on the feature once it has been drawn. To implement these ones is quite a challenge as there is nothing out of the box in the Openlayers library.

@maltaesousa, should I continue with this PR or do you think it would be good to already review this?

2020-11-24 11:19 UTC, maltaesousa commented
This PR is ok, it's better to divide it in small PRs. I'll review this afternoon

2020-11-24 13:02 UTC, maltaesousa requested changes

2020-11-24 13:02 UTC, maltaesousa commented on front/src/assets/configs/config.json.tmpl
> +    }
```suggestion
  "pageformats": [
    {
      "name": "A4",
      "width": 210,
      "height": 297
    },
    {
      "name": "A3",
      "width": 297,
      "height": 420
    },
    {
      "name": "A2",
      "width": 420,
      "height": 594
    },
    {
      "name": "A1",
      "width": 594,
      "height": 841
    },
    {
      "name": "A0",
      "width": 841,
      "height": 1189
    }
```

2020-11-25 09:46 UTC, kalbermattenm commented on front/src/app/_services/map.service.ts
> +    const h = format.height / 72 / INCHES_PER_METER_UNIT * scale / 2;
If you are sure about the `2000` factor, I am happy to merge...

2020-11-25 09:47 UTC, kalbermattenm commented on front/src/app/welcome/map/map.component.ts
> +      width: '250px',
Actually, this is an official option of the Angular Material ` MatDialogConfig` documentation.

2020-11-25 09:48 UTC, kalbermattenm commented
I got some conflicts on this branch. Resolving them now.

2020-11-25 09:52 UTC, merged